#!/usr/bin/env bash

version=$1

if [[ -z "$version" ]]; then
  echo "usage: $0 <version-number>"
  exit 1
fi

git_sha=`git rev-parse --short HEAD`
version_with_sha="${version}+${git_sha}"

if [ -d build ]; then
  rm -rf build
fi
mkdir -p build

platforms=("windows/amd64" "linux/amd64" "darwin/amd64")

echo "==> Build started for v${version}"

for platform in "${platforms[@]}"
do
  platform_split=(${platform//\// })
  GOOS=${platform_split[0]}
  GOARCH=${platform_split[1]}
  output_name="logshare-cli_${version}_${GOOS}_${GOARCH}"

  if [ $GOOS = "windows" ]; then
    printf "==> Building %s\t%s\n" "$platform" "build/$output_name.exe" | expand -t 30
    env GOOS=$GOOS GOARCH=$GOARCH go build -o "build/${output_name}.exe" -ldflags "-X main.Rev=${version_with_sha}" cmd/logshare-cli/main.go
  else
    printf "==> Building %s\t%s\n" "$platform" "build/$output_name" | expand -t 30
    env GOOS=$GOOS GOARCH=$GOARCH go build -o "build/${output_name}" -ldflags "-X main.Rev=${version_with_sha}" cmd/logshare-cli/main.go
  fi
  if [ $? -ne 0 ]; then
    echo "Building the binary has failed!"
    exit 1
  fi
done

echo "==> Generating file checksums to build/checksums.txt"
shasum -a 256 build/* > "build/checksums.txt"

echo "==> Build process complete"
